/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    ComparePanel: typeof import('./src/components/ComparePanel.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    Message: typeof import('primevue/message')['default']
    Tag: typeof import('primevue/tag')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
  }
}
